Sales/Sales.Backend/Controllers/ProductsLuisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sales.Backend.Models;
using Sales.Common.Models;
using Sales.Backend.Helpers;

namespace Sales.Backend.Controllers
{

    [Authorize]
    public class ProductsLuisController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: ProductsLuis
        public async Task<ActionResult> Index()
        {
            return View(await db.ProductsLuis.OrderBy(p => p.NOM_PROD_VAR).ToListAsync());
        }

        // GET: ProductsLuis/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsLuis productsLuis = await db.ProductsLuis.FindAsync(id);
            if (productsLuis == null)
            {
                return HttpNotFound();
            }
            return View(productsLuis);
        }

        // GET: ProductsLuis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsLuis/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/ProductsLuis";

                if (view.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var product = this.ToProduct(view, pic);
                this.db.ProductsLuis.Add(product);
                await this.db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        private ProductsLuis ToProduct(ProductView view, string pic)
        {
            return new ProductsLuis
            {
                NOM_PROD_VAR  = view.NOM_PROD_VAR ,
                RUTA_IMAGEN_VAR  = pic,
                IS_AVAILABLE_BIT  = view.IS_AVAILABLE_BIT ,
                PRECIO_DEC  = view.PRECIO_DEC ,
                CVE_PRODUCTO_VAR  = view.CVE_PRODUCTO_VAR ,
                PUBLISH_ON_DATE  = view.PUBLISH_ON_DATE ,
                REMARK_VAR  = view.REMARK_VAR,
                UNIDAD_MEDIDA_VAR = view.UNIDAD_MEDIDA_VAR ,
            };
        }


        // GET: ProductsLuis/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }

            var product = await this.db.ProductsLuis.FindAsync(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            var view = this.ToView(product);
            return View(view);
        }

        private ProductView ToView(ProductsLuis  product)
        {
            return new ProductView
            {
                NOM_PROD_VAR  = product.NOM_PROD_VAR ,
                RUTA_IMAGEN_VAR  = product.RUTA_IMAGEN_VAR ,
                IS_AVAILABLE_BIT  = product.IS_AVAILABLE_BIT ,
                PRECIO_DEC  = product.PRECIO_DEC ,
                CVE_PRODUCTO_VAR  = product.CVE_PRODUCTO_VAR ,
                PUBLISH_ON_DATE  = product.PUBLISH_ON_DATE ,
                REMARK_VAR  = product.REMARK_VAR ,
                UNIDAD_MEDIDA_VAR = product .UNIDAD_MEDIDA_VAR,
            };
        }

        // POST: ProductsLuis/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductView view)
        {
            if (ModelState.IsValid)
            {
                var pic = view.RUTA_IMAGEN_VAR ;
                var folder = "~/Content/ProductsLuis";

                if (view.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var product = this.ToProduct(view, pic);
                this.db.Entry(product).State = EntityState.Modified;
                await this.db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        // GET: ProductsLuis/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsLuis productsLuis = await db.ProductsLuis.FindAsync(id);
            if (productsLuis == null)
            {
                return HttpNotFound();
            }
            return View(productsLuis);
        }

        // POST: ProductsLuis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var productsLuis = await db.ProductsLuis.FindAsync(id);
            db.ProductsLuis.Remove(productsLuis);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sales/Sales.Backend/Views/ProductsLuis/Create.cshtml
@model Sales.Backend.Models.ProductView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ProductsLuis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ProductsLuis</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CVE_PRODUCTO_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CVE_PRODUCTO_VAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CVE_PRODUCTO_VAR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NOM_PROD_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NOM_PROD_VAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NOM_PROD_VAR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.REMARK_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.REMARK_VAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.REMARK_VAR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span class="btn btn-default btn-file">
                @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
            </span>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PRECIO_DEC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PRECIO_DEC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PRECIO_DEC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UNIDAD_MEDIDA_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UNIDAD_MEDIDA_VAR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UNIDAD_MEDIDA_VAR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IS_AVAILABLE_BIT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IS_AVAILABLE_BIT)
                @Html.ValidationMessageFor(model => model.IS_AVAILABLE_BIT, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PUBLISH_ON_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PUBLISH_ON_DATE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PUBLISH_ON_DATE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sales/Sales.Backend/Views/ProductsLuis/Delete.cshtml
@model Sales.Common.Models.ProductsLuis

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductsLuis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOM_PROD_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM_PROD_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.REMARK_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REMARK_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RUTA_IMAGEN_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RUTA_IMAGEN_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRECIO_DEC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRECIO_DEC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIDAD_MEDIDA_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIDAD_MEDIDA_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_AVAILABLE_BIT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_AVAILABLE_BIT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PUBLISH_ON_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PUBLISH_ON_DATE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index" , new { }, new { @class = "btn btn-success" })
        </div>
    }
</div>

Sales/Sales.Backend/Views/ProductsLuis/Details.cshtml
@model Sales.Common.Models.ProductsLuis

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProductsLuis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOM_PROD_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOM_PROD_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.REMARK_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REMARK_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RUTA_IMAGEN_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RUTA_IMAGEN_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRECIO_DEC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRECIO_DEC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIDAD_MEDIDA_VAR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIDAD_MEDIDA_VAR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IS_AVAILABLE_BIT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IS_AVAILABLE_BIT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PUBLISH_ON_DATE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PUBLISH_ON_DATE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CVE_PRODUCTO_VAR }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sales/Sales.Backend/Views/ProductsLuis/Edit.cshtml
@model Sales.Backend.Models.ProductView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ProductsLuis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductsLuis</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CVE_PRODUCTO_VAR)
        @Html.HiddenFor(model => model.RUTA_IMAGEN_VAR)

        <div class="form-group">
            @Html.LabelFor(model => model.NOM_PROD_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOM_PROD_VAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOM_PROD_VAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.REMARK_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REMARK_VAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REMARK_VAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRECIO_DEC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRECIO_DEC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRECIO_DEC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UNIDAD_MEDIDA_VAR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UNIDAD_MEDIDA_VAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UNIDAD_MEDIDA_VAR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IS_AVAILABLE_BIT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IS_AVAILABLE_BIT)
                    @Html.ValidationMessageFor(model => model.IS_AVAILABLE_BIT, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PUBLISH_ON_DATE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PUBLISH_ON_DATE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PUBLISH_ON_DATE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class="btn btn-success"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sales/Sales.Backend/Views/ProductsLuis/Index.cshtml
@model IEnumerable<Sales.Common.Models.ProductsLuis >

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new {@class="btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOM_PROD_VAR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.REMARK_VAR)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.RUTA_IMAGEN_VAR )
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PRECIO_DEC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UNIDAD_MEDIDA_VAR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IS_AVAILABLE_BIT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PUBLISH_ON_DATE)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOM_PROD_VAR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.REMARK_VAR)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.RUTA_IMAGEN_VAR))
            {
                <img src="@Url.Content(item.ImageFullPath)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PRECIO_DEC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UNIDAD_MEDIDA_VAR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IS_AVAILABLE_BIT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PUBLISH_ON_DATE)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CVE_PRODUCTO_VAR }, new { @class="btn btn-warning"}) |
            @Html.ActionLink("Details", "Details", new { id=item.CVE_PRODUCTO_VAR }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CVE_PRODUCTO_VAR }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>